version: '3'
services:
  app:
    build: .
    ports:
      - '8500:5000'
    volumes:
      - ./:/app
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=main.py
      - PYTHONUNBUFFERED=1
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
